export const cities = [
  { id: 'mumbai', name: 'Mumbai', propertyCount: 425, coordinates: { lat: 19.0760, lng: 72.8777 } },
  { id: 'thane', name: 'Thane', propertyCount: 312, coordinates: { lat: 19.2183, lng: 72.9781 } },
  { id: 'pune', name: 'Pune', propertyCount: 380, coordinates: { lat: 18.5204, lng: 73.8567 } },
  { id: 'nashik', name: 'Nashik', propertyCount: 145, coordinates: { lat: 20.0110, lng: 73.7903 } },
  { id: 'aurangabad', name: 'Aurangabad', propertyCount: 92, coordinates: { lat: 19.8762, lng: 75.3433 } },
  { id: 'nagpur', name: 'Nagpur', propertyCount: 189, coordinates: { lat: 21.1458, lng: 79.0882 } },
  { id: 'kolhapur', name: 'Kolhapur', propertyCount: 65, coordinates: { lat: 16.7050, lng: 74.2433 } },
  { id: 'solapur', name: 'Solapur', propertyCount: 54, coordinates: { lat: 17.6599, lng: 75.9064 } },
  { id: 'amravati', name: 'Amravati', propertyCount: 41, coordinates: { lat: 20.9320, lng: 77.7523 } },
  { id: 'jalgaon', name: 'Jalgaon', propertyCount: 38, coordinates: { lat: 21.0077, lng: 75.5626 } },
  { id: 'nanded', name: 'Nanded', propertyCount: 47, coordinates: { lat: 19.1383, lng: 77.3210 } },
];

export const agents = [
  { id: 'agt-1', name: 'Aniket Deshmukh', phone: '+91 98230 12345', email: 'aniket.d@mahaauctions.com', rating: 4.9, specialty: 'Bank Auctions', image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80' },
  { id: 'agt-2', name: 'Meera Kulkarni', phone: '+91 98901 67890', email: 'meera.k@mahaauctions.com', rating: 4.8, specialty: 'Premium Rentals & Heavy Deposit', image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80' },
  { id: 'agt-3', name: 'Sanjay Patil', phone: '+91 91582 34567', email: 'sanjay.p@mahaauctions.com', rating: 4.7, specialty: 'Commercial & Industrial Listings', image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80' }
];

export const properties = [
  // BANK AUCTION PROPERTIES
  {
    id: 'prop-1',
    listingId: 'MA-2026-001',
    cityId: 'mumbai',
    title: '3 BHK Sea-facing Apartment in Worli',
    type: 'Residential',
    category: 'Auction',
    address: 'A-Wing, 14th Floor, Sea View Heights, Worli, Mumbai',
    reservePrice: '₹ 4.50 Cr',
    numericPrice: 45000000,
    emd: '₹ 45.00 Lakhs',
    governmentValuation: '₹ 5.80 Cr',
    numericGovValuation: 58000000,
    auctionDate: '2026-06-15T11:00:00Z',
    bank: 'State Bank of India',
    borrower: 'Rajesh Sharma',
    possession: 'Physical',
    agentId: 'agt-1',
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
    details: 'Spacious 3 BHK apartment with unobstructed sea views. Building features premium amenities including pool, gym, and 24/7 security.',
    noticeEnglish: 'PUBLIC NOTICE FOR E-AUCTION: Under Sec 13(2) of SARFAESI Act, 2002. Notice is hereby given that the secured asset described herein will be sold on "As is where is basis" for recovery of bank dues of ₹4.12 Cr. Reserve Price: ₹4.50 Cr. EMD: ₹45 Lakhs.',
    noticeMarathi: 'ई-लिलाव जाहीर नोटीस: सिक्युरिटायझेशन कायद्याच्या कलम १३(२) अंतर्गत जाहीर नोटीस. याद्वारे कळविण्यात येते की बँकेच्या थकीत रु. ४.१२ कोटी वसुलीसाठी सदर मालमत्ता "आहे त्या स्थितीत" लिलावात काढण्यात येत आहे. राखीव किंमत: रु. ४.५० कोटी. इसारा ठेव (EMD): रु. ४५ लाख.'
  },
  {
    id: 'prop-2',
    listingId: 'MA-2026-002',
    cityId: 'mumbai',
    title: 'Commercial Office Space in BKC',
    type: 'Commercial',
    category: 'Auction',
    address: 'Unit 402, 4th Floor, Platinum Tower, BKC, Mumbai',
    reservePrice: '₹ 12.00 Cr',
    numericPrice: 120000000,
    emd: '₹ 1.20 Cr',
    governmentValuation: '₹ 15.50 Cr',
    numericGovValuation: 155000000,
    auctionDate: '2026-06-20T10:30:00Z',
    bank: 'ICICI Bank',
    borrower: 'TechVision Solutions Pvt Ltd',
    possession: 'Symbolic',
    agentId: 'agt-3',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    details: 'Prime commercial office space in Bandra Kurla Complex. Fully furnished with 50 workstations, 2 executive cabins, and 2 large conference rooms.',
    noticeEnglish: 'SALE NOTICE FOR SALE OF IMMOVABLE PROPERTY: under Rule 8(6) of Security Interest Rules. ICICI Bank hereby invites online bids for symbolic possession property at BKC. Dues: ₹10.85 Cr. Reserve Price: ₹12.00 Cr.',
    noticeMarathi: 'स्थावर मालमत्ता विक्री नोटीस: सिक्युरिटीं इंटरेस्ट नियमांच्या नियम ८(६) अन्वये विक्री नोटीस. आयसीआयसीआय बँक याद्वारे बीकेसी येथील मालमत्तेसाठी ऑनलाईन बोली मागवित आहे. राखीव किंमत: रु. १२.०० कोटी. इसारा ठेव: रु. १.२० कोटी.'
  },

  // HEAVY DEPOSIT PROPERTIES
  {
    id: 'prop-3',
    listingId: 'MA-2026-003',
    cityId: 'mumbai',
    title: '2 BHK Premium Flat - Heavy Deposit',
    type: 'Residential',
    category: 'Heavy Deposit',
    address: 'Sector 4, Hiranandani Meadows, Thane West, Mumbai',
    reservePrice: '₹ 25.00 Lakhs (Deposit Only)',
    numericPrice: 2500000,
    emd: 'N/A',
    monthlyRent: '₹ 0 / Month',
    deposit: '₹ 25.00 Lakhs',
    governmentValuation: '₹ 32.00 Lakhs (Normal Market Deposit Equivalent)',
    numericGovValuation: 3200000,
    auctionDate: 'Available Immediately',
    bank: 'N/A (Seller Listed)',
    borrower: 'N/A',
    possession: 'Ready to Move',
    agentId: 'agt-2',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
    details: 'Classic Heavy Deposit option. Pay ₹25 Lakhs refundable deposit with ZERO monthly rent for 2 years. Premium semi-furnished flat in Hiranandani with modern kitchen and high-speed elevator.',
    noticeEnglish: 'HEAVY DEPOSIT AGREEMENT: Secure agreement of tenure 24 months. Refundable security deposit of ₹25,000,000 paid at registration. Agreement registered via government portal.',
    noticeMarathi: 'हेवी डिपॉझिट करारनामा: २४ महिन्यांच्या कालावधीसाठी सुरक्षित करार. नोंदणीच्या वेळी २५,००,००० रुपये परतावायोग्य ठेव रक्कम. शासकीय नोंदणीकृत भाडे करारनामा केला जाईल.'
  },

  // RENTAL PROPERTIES
  {
    id: 'prop-4',
    listingId: 'MA-2026-004',
    cityId: 'pune',
    title: '4 BHK Luxury Villa for Rent in Koregaon Park',
    type: 'Residential',
    category: 'Rental',
    address: 'Villa No. 7, Silver Oaks Society, Koregaon Park, Pune',
    reservePrice: '₹ 1.80 Lakhs / Month',
    numericPrice: 180000,
    emd: 'N/A',
    monthlyRent: '₹ 1.80 Lakhs',
    deposit: '₹ 5.00 Lakhs',
    governmentValuation: '₹ 2.20 Lakhs / Month (Market Avg Rent)',
    numericGovValuation: 220000,
    auctionDate: 'Available for Rent',
    bank: 'N/A',
    borrower: 'N/A',
    possession: 'Immediate Occupancy',
    agentId: 'agt-2',
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80',
    details: 'Independent luxury villa for rent. Private manicured garden, swimming pool, imported modular kitchen, servant quarters, and solar panel grid installed.',
    noticeEnglish: 'LEASING PUBLIC OPPORTUNITY: Luxury Pune residency open for corporate or family lease. Terms are negotiable with 3 months rent in advance as security deposit.',
    noticeMarathi: 'भाडेतत्वावर देणे आहे: कोरेगाव पार्क येथील अलिशान स्वतंत्र व्हिला कॉर्पोरेट किंवा खाजगी कुटुंबासाठी भाड्याने देणे आहे. अनामत रक्कम: ५ लाख, मासिक भाडे: १.८० लाख.'
  },

  // SELLER LISTED PROPERTIES (Sale)
  {
    id: 'prop-5',
    listingId: 'MA-2026-005',
    cityId: 'pune',
    title: 'Premium Penthouse with Rooftop Deck',
    type: 'Residential',
    category: 'Seller Listed',
    address: 'B-Wing, 12th Floor, Trump Towers, Kalyani Nagar, Pune',
    reservePrice: '₹ 8.20 Cr',
    numericPrice: 82000000,
    emd: 'N/A',
    governmentValuation: '₹ 9.50 Cr',
    numericGovValuation: 95000000,
    auctionDate: 'Negotiable Sale',
    bank: 'N/A',
    borrower: 'N/A',
    possession: 'Physical Possession',
    agentId: 'agt-1',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    details: 'Exquisite builder-floor penthouse directly listed by the owner. Features double-height ceilings, a huge rooftop deck with skyline views, automation controls, and custom marble styling.',
    noticeEnglish: 'EXCELLENT DIRECT PRIVATE INVESTMENT SALE: Clear title verified property available for direct purchase from the owner. Price ₹8.20 Cr (market savings of ₹1.3 Cr below government ready reckoner valuation).',
    noticeMarathi: 'थेट मालकाकडून विक्री: कायदेशीर मालकी हक्क पडताळणी केलेली मालमत्ता थेट खरेदीसाठी उपलब्ध आहे. किंमत रु. ८.२० कोटी (शासकीय रेडी रेकनर दरापेक्षा १.३ कोटी बचत).'
  },

  // INDUSTRIAL / INDUSTRIAL AUCTION
  {
    id: 'prop-6',
    listingId: 'MA-2026-006',
    cityId: 'pune',
    title: 'Industrial Shed in Bhosari MIDC',
    type: 'Industrial',
    category: 'Auction',
    address: 'Plot No. J-24, Bhosari MIDC, Pune',
    reservePrice: '₹ 2.80 Cr',
    numericPrice: 28000000,
    emd: '₹ 28.00 Lakhs',
    governmentValuation: '₹ 3.50 Cr',
    numericGovValuation: 35000000,
    auctionDate: '2026-06-25T14:00:00Z',
    bank: 'Bank of Baroda',
    borrower: 'Precision Engineering Works',
    possession: 'Physical',
    agentId: 'agt-3',
    image: 'https://images.unsplash.com/photo-1580982327559-c1202864eb05?auto=format&fit=crop&w=800&q=80',
    details: 'Heavy-duty industrial manufacturing shed. Features high power load capacity (100 HP), overhead gantry crane tracks (5 Ton capacity), concrete flooring, and clear height of 24 feet.',
    noticeEnglish: 'SARFAESI ACT 2002 NOTICE: Secure assets of Precision Engineering Works will be sold online via e-auction for recovery of dues ₹2.45 Cr. Auction scheduled under Section 13(4) of Act.',
    noticeMarathi: 'सरफेसी कायदा २००२ नोटीस: प्रिसिजन इंजिनिअरिंग वर्क्सच्या तारण मालमत्तेचा थकबाकी २.४५ कोटी वसुलीसाठी ई-लिलाव. कलम १३(४) अन्वये विक्री जाहीर करण्यात आली आहे.'
  },

  // AGRICULTUAL LAND AUCTION
  {
    id: 'prop-7',
    listingId: 'MA-2026-007',
    cityId: 'nashik',
    title: 'Grape Vineyard with Farmhouse in Dindori',
    type: 'Agricultural',
    category: 'Auction',
    address: 'Survey No. 45, Dindori Grape Valley, Nashik',
    reservePrice: '₹ 3.20 Cr',
    numericPrice: 32000000,
    emd: '₹ 32.00 Lakhs',
    governmentValuation: '₹ 4.10 Cr',
    numericGovValuation: 41000000,
    auctionDate: '2026-07-15T10:00:00Z',
    bank: 'Central Bank of India',
    borrower: 'Vineyards Estate Pvt Ltd',
    possession: 'Physical',
    agentId: 'agt-1',
    image: 'https://images.unsplash.com/photo-1552594612-9c3f256a4276?auto=format&fit=crop&w=800&q=80',
    details: '10-acre fully operational premium grape vineyard in Dindori valley. Includes drip irrigation systems, warehouse storage, water borewells, and a beautiful 2 BHK boutique farmhouse.',
    noticeEnglish: 'PUBLIC TENDER AUCTION: Sale under SARFAESI Security Interest Enforcement. 10 acres agricultural grape farm. All assets mortgaged under Central Bank of India will be auctioned online.',
    noticeMarathi: 'सार्वजनिक निविदा लिलाव: सरफेसी कायद्यांतर्गत विक्री नोटीस. सेंट्रल बँक ऑफ इंडियाकडे तारण असलेली १० एकर द्राक्ष शेती व फार्महाऊस ऑनलाईन लिलावात विक्रीसाठी उपलब्ध.'
  },

  // THANE
  {
    id: 'prop-8',
    listingId: 'MA-2026-008',
    cityId: 'thane',
    title: 'Spacious 3 BHK in Hiranandani Estate',
    type: 'Residential',
    category: 'Auction',
    address: 'Tower 4, Hiranandani Estate, Ghodbunder Road, Thane',
    reservePrice: '₹ 2.10 Cr',
    numericPrice: 21000000,
    emd: '₹ 21.00 Lakhs',
    governmentValuation: '₹ 2.70 Cr',
    numericGovValuation: 27000000,
    auctionDate: '2026-07-10T11:00:00Z',
    bank: 'Kotak Mahindra Bank',
    borrower: 'Sunil Gavaskar Ltd',
    possession: 'Physical',
    agentId: 'agt-2',
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80',
    details: 'High-floor premium luxury residence in Hiranandani Estate, Thane. Exquisite fittings, massive marble tiling, dynamic cross ventilation, and scenic views of the surrounding hills.',
    noticeEnglish: 'SALE PROCLAMATION FOR E-AUCTION: Under SARFAESI security enforcement guidelines. Bank dues amount to ₹1.95 Cr. Bids strictly accepted on e-portal until auction day.',
    noticeMarathi: 'ई-लिलाव विक्री घोषणापत्र: सरफेसी सुरक्षा कायद्याअंतर्गत नोटीस. कोटक महिंद्रा बँकेचे रु. १.९५ कोटी थकबाकी वसुलीसाठी लिलाव. बोली केवळ अधिकृत वेब पोर्टलवर स्वीकारली जाईल.'
  }
];

export const advocatesList = [
  {
    id: 'sajid',
    name: 'Adv. Sajid Kureshi',
    role: 'Chief Founder & Senior Counsel',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&h=150&q=80',
    barReg: 'MAH/2084/2007',
    education: 'LL.M (Banking & Finance), GLC Mumbai',
    experience: '18+ Years Practice',
    office: 'Chamber 12, Court Building Suites (CBS), Opp. District Court, Nashik - 422002',
    phone: '+91 96044 96521',
    email: 'sajid.kureshi@mahaauctions-adv.in',
    rating: '4.95 (142 reviews)',
    specialties: 'SARFAESI 13(2)/13(4) disputes, Physical DM Possession recovery, Banking Arbitration',
    trustScore: '99.4% Success Rate',
    bio: 'Adv. Sajid Kureshi is the chief legal architect of MahaAuctions. He has successfully cleared over 500+ statutory bank recovery disputes before the DRT and High Court.'
  },
  {
    id: 'smita',
    name: 'Adv. Smita Patil',
    role: 'Premium Sponsored Partner',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
    barReg: 'MAH/5829/2014',
    education: 'LL.B, ILS Law College, Pune',
    experience: '12+ Years Practice',
    office: 'Office 12, Gold Plaza, Senapati Bapat Road, Pune - 411016',
    phone: '+91 99230 58291',
    email: 'smita.patil@patilchambers.com',
    rating: '4.90 (89 reviews)',
    specialties: 'RERA Compliance, Heavy Deposit Lease covenants, Title Search clearance',
    trustScore: '98.1% Clearance Rate',
    bio: 'Adv. Smita Patil is a leading property arbitrator in Pune, assisting auction buyers in conducting comprehensive pre-purchase title searches.'
  },
  {
    id: 'rohan',
    name: 'Adv. Rohan Mehta',
    role: 'Panel Advocate',
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&q=80',
    barReg: 'MAH/1092/2017',
    education: 'LL.B, Symbiosis Law School, Pune',
    experience: '9+ Years Practice',
    office: 'Chamber 3B, Court Chambers, Shivaji Nagar, Pune - 411005',
    phone: '+91 97662 10928',
    email: 'rohan.mehta@mehtalegal.in',
    rating: '4.85 (56 reviews)',
    specialties: 'DRT Appeals, EMD Disputes, Banking Settlements',
    trustScore: '97.6% Recovery Rate',
    bio: 'Adv. Rohan Mehta specializes in securing quick EMD refund approvals from public sector banks when legal procedures get stalled.'
  },
  {
    id: 'neha',
    name: 'Adv. Neha Kulkarni',
    role: 'Panel Advocate',
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80',
    barReg: 'MAH/4028/2015',
    education: 'B.A. LL.B, GLC Mumbai',
    experience: '11+ Years Practice',
    office: 'Chamber 104, High Court Lane, Fort, Mumbai - 400001',
    phone: '+91 98920 40281',
    email: 'neha.kulkarni@kulkarnilegal.com',
    rating: '4.88 (72 reviews)',
    specialties: 'Asset diligence search, Commercial title reports, Society tax clearances',
    trustScore: '98.5% Accuracy Rate',
    bio: 'Adv. Neha Kulkarni is known for her microscopic inspection of land registries, preventing unexpected municipal or cooperative liabilities.'
  },
  {
    id: 'amit',
    name: 'Adv. Amit Deshmukh',
    role: 'Panel Advocate',
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=150&q=80',
    barReg: 'MAH/6721/2018',
    education: 'LL.B, ILS Pune',
    experience: '8+ Years Practice',
    office: 'Room 5, District Court Chambers, Nashik - 422002',
    phone: '+91 94220 67219',
    email: 'amit.deshmukh@deshmukhchambers.in',
    rating: '4.82 (44 reviews)',
    specialties: 'SARFAESI Rule 8(6) / 13(4) challenges, DM possession applications',
    trustScore: '96.9% Attachment Clearance',
    bio: 'Adv. Amit Deshmukh coordinates directly with local collector offices in Nashik and Aurangabad to resolve DM attachment administrative delays.'
  }
];
